# Generated by Django 4.1.4 on 2023-02-01 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionchoice',
            name='choice_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
    ]
