# Generated by Django 4.2 on 2023-05-12 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='next_question_in_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='questions.question'),
        ),
    ]
