# Generated by Django 4.2.2 on 2023-06-07 12:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_next_question_in_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_body',
            field=tinymce.models.HTMLField(),
        ),
    ]
