# Generated by Django 4.2.2 on 2023-06-07 12:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_question_question_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_explanation',
            field=tinymce.models.HTMLField(),
        ),
    ]
