# Generated by Django 4.1.7 on 2023-02-26 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='owner',
        ),
    ]
