# Generated by Django 4.1.7 on 2023-03-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_question_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionchoice',
            name='choice_text',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
