# Generated by Django 4.1.7 on 2023-03-06 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_alter_questionchoice_choice_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionchoice',
            name='choice_text',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
