# Generated by Django 4.2.1 on 2023-05-29 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0008_alter_tile_type_of_tile_char'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='folder.tile', verbose_name='parent'),
        ),
    ]
