# Generated by Django 4.2.5 on 2024-01-30 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0009_alter_tile_parent'),
    ]

    operations = [
        migrations.RenameModel('Tile', 'Folder')
    ]
