# Generated by Django 4.1.7 on 2023-03-12 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home_page_tiles', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteRequestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_reward', models.FloatField(default=1, null=True)),
                ('block_mode', models.IntegerField(choices=[(1, 'Test'), (2, 'Training')])),
                ('block_sector', models.IntegerField(choices=[(1, 'Private'), (2, 'Public')])),
                ('timed', models.BooleanField(default=False)),
                ('block_total_questions', models.IntegerField()),
                ('finished', models.BooleanField(default=False)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_correct', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tile_created_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home_page_tiles.homepagetile')),
            ],
        ),
    ]
