# Generated by Django 4.1.7 on 2023-03-17 07:23

from django.db import migrations, models
import tiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='tile_headline',
            field=models.CharField(max_length=128, validators=[tiles.models.headline_unique]),
        ),
    ]
