# Generated by Django 4.1.4 on 2023-02-01 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_tiles', '0002_remove_homepagetile_creation_date'),
        ('tiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writerequestdata',
            name='tile_created_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home_page_tiles.homepagetile'),
        ),
    ]
