# Generated by Django 4.1.7 on 2023-03-26 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tile',
            name='children',
        ),
        migrations.AddField(
            model_name='tile',
            name='children',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tiles.tile'),
        ),
    ]
