# Generated by Django 4.1.7 on 2023-03-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0003_rename_children_tile_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='tile_headline',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
