# Generated by Django 4.1.7 on 2023-04-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('tiles', '0004_alter_tile_tile_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='tile', to='questions.question'),
        ),
    ]
