# Generated by Django 4.2 on 2023-04-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answer_state',
            field=models.IntegerField(choices=[(1, 'Unseen'), (2, 'Seen'), (3, 'Selected'), (4, 'Answered'), (5, 'Correct'), (6, 'Incorrect'), (7, 'Unselected Timeout'), (8, 'Selected Timeout')], default=1),
        ),
    ]
