# Generated by Django 4.2 on 2023-04-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0002_alter_useranswer_answer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answer_state',
            field=models.IntegerField(choices=[(1, 'Unseen'), (2, 'Seen'), (4, 'Selected'), (8, 'Answered'), (16, 'Correct'), (32, 'Incorrect'), (64, 'Unselected Timeout'), (128, 'Selected Timeout')], default=1),
        ),
    ]
