# Generated by Django 4.2.2 on 2023-06-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0004_alter_useranswer_answer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answer_state',
            field=models.IntegerField(choices=[(1, 'Seen'), (2, 'Selected'), (4, 'Submitted'), (8, 'Correct'), (16, 'Timeout')], default=0),
        ),
    ]
