# Generated by Django 4.2.5 on 2024-02-04 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0012_alter_folder_name_alter_folder_parent_and_more'),
        ('writing', '0005_alter_useranswer_answer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='wrd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folder.writerequestdata'),
        ),
    ]
