# Generated by Django 4.1.7 on 2023-03-12 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0010_alter_questionchoice_choice_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile_headline', models.CharField(max_length=128)),
                ('pointer_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('subtype_of_tile', models.IntegerField(blank=True, null=True)),
                ('img_url', models.URLField(blank=True, null=True)),
                ('type_of_tile_char', models.CharField(choices=[('T', 'Tag'), ('B', 'Block'), ('O', 'Official Test'), ('S', 'Subject'), ('U', 'Organization'), ('K', 'Book'), ('C', 'Chapter'), ('P', 'Page'), ('C', 'Course'), ('R', 'Research Paper'), ('Q', 'Question')], max_length=1)),
                ('json_data_tags', models.JSONField(default=dict)),
                ('expected_reward', models.FloatField(blank=True, null=True)),
                ('total_questions', models.IntegerField(blank=True, null=True)),
                ('total_pass', models.IntegerField(default=0)),
                ('total_writes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('children', models.ManyToManyField(to='home_page_tiles.homepagetile')),
                ('questions', models.ManyToManyField(to='questions.question')),
            ],
        ),
    ]
