# Generated by Django 4.1.5 on 2023-01-31 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TilesTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home_page_tiles.tilestag')),
                ('tiles_tag_children', models.ManyToManyField(blank=True, to='home_page_tiles.tilestag')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile_headline', models.CharField(max_length=128)),
                ('pointer_url', models.URLField(blank=True, null=True)),
                ('type_of_tile_char', models.CharField(choices=[('T', 'Tag'), ('B', 'Block'), ('O', 'Official Test'), ('S', 'Subject'), ('U', 'Organization'), ('K', 'Book'), ('C', 'Chapter'), ('P', 'Page'), ('C', 'Course'), ('R', 'Research Paper')], max_length=1)),
                ('json_data_tags', models.JSONField(default=dict)),
                ('subtype_of_tile', models.IntegerField(blank=True, null=True)),
                ('img_url', models.URLField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('expected_reward', models.FloatField(blank=True, null=True)),
                ('total_questions', models.IntegerField(blank=True, null=True)),
                ('total_pass', models.IntegerField(default=0)),
                ('total_writes', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_accounts.profile')),
                ('tags', models.ManyToManyField(to='home_page_tiles.tilestag')),
            ],
        ),
    ]
