# Generated by Django 4.1.5 on 2023-01-31 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_tiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagetile',
            name='creation_date',
        ),
    ]
