# Generated by Django 4.1.7 on 2023-03-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_question_owner'),
        ('home_page_tiles', '0002_remove_homepagetile_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagetile',
            name='tags',
        ),
        migrations.AddField(
            model_name='homepagetile',
            name='children',
            field=models.ManyToManyField(null=True, to='home_page_tiles.homepagetile'),
        ),
        migrations.AddField(
            model_name='homepagetile',
            name='questions',
            field=models.ManyToManyField(null=True, to='questions.question'),
        ),
        migrations.AlterField(
            model_name='homepagetile',
            name='type_of_tile_char',
            field=models.CharField(choices=[('T', 'Tag'), ('B', 'Block'), ('O', 'Official Test'), ('S', 'Subject'), ('U', 'Organization'), ('K', 'Book'), ('C', 'Chapter'), ('P', 'Page'), ('C', 'Course'), ('R', 'Research Paper'), ('Q', 'Question')], max_length=1),
        ),
        migrations.DeleteModel(
            name='TilesTag',
        ),
    ]
