# Generated by Django 4.1.7 on 2023-03-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_question_owner'),
        ('home_page_tiles', '0003_remove_homepagetile_tags_homepagetile_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagetile',
            name='children',
            field=models.ManyToManyField(to='home_page_tiles.homepagetile'),
        ),
        migrations.AlterField(
            model_name='homepagetile',
            name='questions',
            field=models.ManyToManyField(to='questions.question'),
        ),
    ]
