# Generated by Django 4.1.7 on 2023-03-04 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home_page_tiles', '0004_alter_homepagetile_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagetile',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
