# Generated by Django 4.1.5 on 2023-01-31 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('tiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choosen_answer', models.IntegerField(null=True)),
                ('answer_state', models.IntegerField(choices=[(1, 'Unseen'), (2, 'Seen'), (3, 'Answered'), (4, 'Correct'), (5, 'Incorrect'), (6, 'Unselected Timeout'), (7, 'Selected Timeout')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choosen_answer_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.questionchoice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('wrd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiles.writerequestdata')),
            ],
        ),
    ]
