# Generated by Django 4.1.4 on 2023-02-01 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('testwriting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='choosen_answer_obj',
            field=models.ForeignKey(limit_choices_to=models.Q(('choice_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question'))), null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.questionchoice'),
        ),
    ]
