# Generated by Django 4.1.4 on 2023-02-01 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testwriting', '0002_alter_useranswer_choosen_answer_obj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='question',
            new_name='answered_to_question',
        ),
    ]
