# Generated by Django 4.1.4 on 2023-02-01 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testwriting', '0003_rename_question_useranswer_answered_to_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='answered_to_question',
            new_name='answer_to',
        ),
    ]
