# Generated by Django 4.1.4 on 2023-02-01 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_question_correct_choice'),
        ('testwriting', '0004_rename_answered_to_question_useranswer_answer_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='choosen_answer_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.questionchoice'),
        ),
    ]
