# Generated by Django 4.1.5 on 2023-02-05 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_question_correct_choice'),
        ('testwriting', '0005_alter_useranswer_choosen_answer_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='choosen_answer_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.questionchoice'),
        ),
    ]
