# Generated by Django 4.1.7 on 2023-02-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testwriting', '0006_alter_useranswer_choosen_answer_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='block_number',
            field=models.IntegerField(null=True),
        ),
    ]
