# Generated by Django 4.1.7 on 2023-02-26 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testwriting', '0007_useranswer_block_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answer_state',
            field=models.IntegerField(choices=[(1, 'Unseen'), (2, 'Seen'), (3, 'Answered'), (4, 'Correct'), (5, 'Incorrect'), (6, 'Unselected Timeout'), (7, 'Selected Timeout')], default=1),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='choosen_answer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
